[package]
name = "math"
version = "0.1.0"
edition = "2018"

[lib]
name = "math"
path = "src/lib.rs"

[[bench]]
name = "all"
harness = false

[dependencies]
rand = "0.7.3"
common = { path = "../common" }

[dev-dependencies]
criterion = "0.3.3"
num-bigint = "0.3.0"
