[package]
name = "prover"
version = "0.1.0"
edition = "2018"

[lib]
bench = false

[dependencies]
math = { path = "../math" }
crypto = { path = "../crypto" }
common = { path = "../common" }
fri = { path = '../fri' }
log = "0.4.11"
kompact = "0.10.1"

[features]
extension_field = []
