[package]
name = "plasma"
version = "0.1.0"
edition = "2018"

[dependencies]
cxx = { version = "1.0.27"}
libc = "0.2"
rand = "0.8"

[build-dependencies]
cc = "1.0.66"
cxx-build = {version = "1.0.27"}
