[package]
name = "common"
version = "0.1.0"
edition = "2018"

[lib]
name = "common"
path = "src/lib.rs"

[dependencies]
rand = "0.7.3"
math = { path = "../math" }
crypto = { path = "../crypto" }
serde = { version = "1.0.115", features = ["derive"] }