[package]
name = "verifier"
version = "0.1.0"
edition = "2018"

[lib]
name = "verifier"
path = "src/lib.rs"

[dependencies]
math = { path = "../math" }
crypto = { path = "../crypto" }
common = { path = "../common" }
