[package]
name = "crypto"
version = "0.1.0"
edition = "2018"

[lib]
bench = false

[[bench]]
name = "hash"
harness = false

[dependencies]
digest = "0.9.0"
blake3 = "0.3.7"
sha3 = "0.9.1"
serde = { version = "1.0.114", features = ["derive"] }
math = { path = "../math" }

[dev-dependencies]
criterion = "0.3.3"
proptest = "0.10.1"
